<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>CampusGear-d27882c0-7d71-4d0d-97da-548b14740355</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.31">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CampusGear.Data\CampusGear.Data.csproj" />
    <ProjectReference Include="..\CampusGear.Resources\CampusGear.Resources.csproj" />
    <ProjectReference Include="..\CampusGear.Services\CampusGear.Services.csproj" />
  </ItemGroup>

</Project>
